base_url: https://donmelton.com
cdn_url: https://donmelton-blivetllc.netdna-ssl.com
content_width: 640
copyright: { starting_year: 2012, owner: Don Melton }
description: Just another Web geek playing with the Web
google_analytics_account: UA-34447905-1
hidden_files: true
jquery_version: 1.11.3
kramdown: { entity_output: symbolic }
remove_obsolete: true
search_sites: donmelton.com
title: Don Melton
visible_posts: 25
